kind: Deployment

apiVersion: apps/v1

metadata:
  name: flask-deployment
  namespace: flask
spec:
  selector:
    matchLabels:
      app: flask-label
  template:
    metadata:
      labels: flask-label
    spec:
      containers:
      - name: flask-container
        image: vishal200527/flask-app
        ports:
        - containerPort: 5000